// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type InputMe struct {
	UnidadID string `json:"unidad_id"`
}

type Menus struct {
	ID      string  `json:"id"`
	Label   string  `json:"label"`
	Path    string  `json:"path"`
	Icon    string  `json:"icon"`
	Color   string  `json:"color"`
	Grupo   int32   `json:"grupo"`
	Orden   int32   `json:"orden"`
	PadreID *string `json:"padre_id,omitempty"`
}

type Mutation struct {
}

type NewLogin struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Iv64     string `json:"iv64"`
}

type NewLogin2 struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewNotificacion struct {
	Mensaje string    `json:"mensaje"`
	Desde   time.Time `json:"desde"`
	Hasta   time.Time `json:"hasta"`
}

type NewRol struct {
	Nombre      string   `json:"nombre"`
	Descripcion *string  `json:"descripcion,omitempty"`
	Jerarquia   *int32   `json:"jerarquia,omitempty"`
	Permisos    []string `json:"permisos"`
	Menus       []int32  `json:"menus"`
}

type NewSessionKey struct {
	UsuarioID string    `json:"usuario_id"`
	Key       string    `json:"key"`
	Apikey    string    `json:"apikey"`
	Expire    time.Time `json:"expire"`
}

type NewTicket struct {
	Problema string `json:"problema"`
}

type NewTicketRespuesta struct {
	TicketsID string `json:"tickets_id"`
	Respuesta string `json:"respuesta"`
}

type NewUnidad struct {
	Nombre      string   `json:"nombre"`
	Descripcion *string  `json:"descripcion,omitempty"`
	Latitud     *float64 `json:"latitud,omitempty"`
	Longitud    *float64 `json:"longitud,omitempty"`
	Orden       int32    `json:"orden"`
}

type NewUsuario struct {
	Nombres         string       `json:"nombres"`
	Apellido1       string       `json:"apellido1"`
	Apellido2       *string      `json:"apellido2,omitempty"`
	Documento       *string      `json:"documento,omitempty"`
	Celular         *string      `json:"celular,omitempty"`
	Correo          *string      `json:"correo,omitempty"`
	Sexo            *string      `json:"sexo,omitempty"`
	Direccion       *string      `json:"direccion,omitempty"`
	Username        string       `json:"username"`
	Password        string       `json:"password"`
	Foto64          *string      `json:"foto64,omitempty"`
	Latitud         *float64     `json:"latitud,omitempty"`
	Longitud        *float64     `json:"longitud,omitempty"`
	Roles           []*RolUnidad `json:"roles"`
	PermisosSueltos []string     `json:"permisos_sueltos"`
	MenusSueltos    []string     `json:"menus_sueltos"`
}

type NewUsuarioOauth struct {
	Nombres  string  `json:"nombres"`
	Celular  *string `json:"celular,omitempty"`
	Correo   *string `json:"correo,omitempty"`
	Username string  `json:"username"`
	Password string  `json:"password"`
}

type Notificacion struct {
	ID            string    `json:"id"`
	Mensaje       string    `json:"mensaje"`
	CreadoPorID   string    `json:"creado_por_id"`
	Desde         time.Time `json:"desde"`
	Hasta         time.Time `json:"hasta"`
	FechaRegistro time.Time `json:"fecha_registro"`
}

type Permiso struct {
	Metodo        string    `json:"metodo"`
	Nombre        string    `json:"nombre"`
	Descripcion   *string   `json:"descripcion,omitempty"`
	Grupo         string    `json:"grupo"`
	FechaRegistro time.Time `json:"fecha_registro"`
}

type Query struct {
}

type QueryTickets struct {
	Estado *string `json:"estado,omitempty"`
}

type QueryUsuarios struct {
	Rol *string `json:"rol,omitempty"`
}

type RespTickets struct {
	ID            string     `json:"id"`
	UsuarioID     string     `json:"usuario_id"`
	Usuario       string     `json:"usuario"`
	Problema      string     `json:"problema"`
	Estado        string     `json:"estado"`
	FechaRegistro time.Time  `json:"fecha_registro"`
	Respuesta     *string    `json:"respuesta,omitempty"`
	Soporte       *string    `json:"soporte,omitempty"`
	SoporteID     *string    `json:"soporte_id,omitempty"`
	Respondido    *time.Time `json:"respondido,omitempty"`
}

type ResponseLogin struct {
	SessionKey  string      `json:"session_key"`
	SessionTime int32       `json:"session_time"`
	Me          *ResponseMe `json:"me"`
}

type ResponseMe struct {
	Usuario         *Usuario             `json:"usuario"`
	Menus           []*Menus             `json:"menus"`
	Roles           []*ResponseRolMe     `json:"roles"`
	PermisosSueltos []*ResponsePermisoMe `json:"permisos_sueltos"`
}

type ResponsePermisoMe struct {
	Metodo        string    `json:"metodo"`
	Nombre        string    `json:"nombre"`
	Descripcion   *string   `json:"descripcion,omitempty"`
	Grupo         string    `json:"grupo"`
	FechaRegistro time.Time `json:"fecha_registro"`
	FechaAsignado time.Time `json:"fecha_asignado"`
}

type ResponseReporte1 struct {
	Nombre string `json:"nombre"`
	Valor  int32  `json:"valor"`
}

type ResponseReporte2 struct {
	Fecha    time.Time `json:"fecha"`
	FechaStr string    `json:"fecha_str"`
	Valor    int32     `json:"valor"`
}

type ResponseReporte2b struct {
	Mes   string `json:"mes"`
	Valor int32  `json:"valor"`
}

type ResponseRolMe struct {
	Unidad *Unidad `json:"unidad"`
	Rol    *RolMe  `json:"rol"`
}

type ResponseRolUnidad struct {
	RolID      string `json:"rol_id"`
	UnidadID   string `json:"unidad_id"`
	RolName    string `json:"rol_name"`
	UnidadName string `json:"unidad_name"`
}

type ResponseRoles struct {
	ID            string    `json:"id"`
	Nombre        string    `json:"nombre"`
	Descripcion   *string   `json:"descripcion,omitempty"`
	Jerarquia     int32     `json:"jerarquia"`
	FechaRegistro time.Time `json:"fecha_registro"`
	Menus         int32     `json:"menus"`
	Permisos      int32     `json:"permisos"`
	Usuarios      int32     `json:"usuarios"`
}

type ResponseUsuario struct {
	ID              string               `json:"id"`
	Nombres         string               `json:"nombres"`
	Apellido1       string               `json:"apellido1"`
	Apellido2       *string              `json:"apellido2,omitempty"`
	Documento       *string              `json:"documento,omitempty"`
	Celular         *string              `json:"celular,omitempty"`
	Correo          *string              `json:"correo,omitempty"`
	Sexo            *string              `json:"sexo,omitempty"`
	Direccion       *string              `json:"direccion,omitempty"`
	Username        string               `json:"username"`
	FechaRegistro   time.Time            `json:"fecha_registro"`
	FechaUpdate     time.Time            `json:"fecha_update"`
	Estado          bool                 `json:"estado"`
	LastLogin       *time.Time           `json:"last_login,omitempty"`
	OauthID         *string              `json:"oauth_id,omitempty"`
	FotoURL         *string              `json:"foto_url,omitempty"`
	Latitud         *float64             `json:"latitud,omitempty"`
	Longitud        *float64             `json:"longitud,omitempty"`
	Conexiones      int32                `json:"conexiones"`
	Roles           []*ResponseRolUnidad `json:"roles"`
	PermisosSueltos []*ResponsePermisoMe `json:"permisos_sueltos"`
	MenusSueltos    []*Menus             `json:"menus_sueltos"`
}

type Rol struct {
	ID            string               `json:"id"`
	Nombre        string               `json:"nombre"`
	Descripcion   *string              `json:"descripcion,omitempty"`
	Jerarquia     int32                `json:"jerarquia"`
	FechaRegistro time.Time            `json:"fecha_registro"`
	Permisos      []*ResponsePermisoMe `json:"permisos"`
	Menus         []*Menus             `json:"menus"`
}

type RolMe struct {
	ID            string    `json:"id"`
	Nombre        string    `json:"nombre"`
	Descripcion   *string   `json:"descripcion,omitempty"`
	Jerarquia     int32     `json:"jerarquia"`
	FechaRegistro time.Time `json:"fecha_registro"`
}

type RolUnidad struct {
	RolID    string `json:"rol_id"`
	UnidadID string `json:"unidad_id"`
}

type SessionKey struct {
	ID            string    `json:"id"`
	UsuarioID     string    `json:"usuario_id"`
	Key           string    `json:"key"`
	Apikey        string    `json:"apikey"`
	Expire        time.Time `json:"expire"`
	FechaRegistro time.Time `json:"fecha_registro"`
	UserEstado    bool      `json:"user_estado"`
}

type Subscription struct {
}

type Ticket struct {
	ID            string               `json:"id"`
	UsuarioID     string               `json:"usuario_id"`
	Problema      string               `json:"problema"`
	Estado        string               `json:"estado"`
	FechaRegistro time.Time            `json:"fecha_registro"`
	Respuestas    []*TicketsRespuestas `json:"respuestas"`
}

type TicketsRespuestas struct {
	ID            string    `json:"id"`
	TicketsID     string    `json:"tickets_id"`
	UsuarioID     string    `json:"usuario_id"`
	Respuesta     string    `json:"respuesta"`
	FechaRegistro time.Time `json:"fecha_registro"`
}

type Unidad struct {
	ID            string    `json:"id"`
	Nombre        string    `json:"nombre"`
	Descripcion   *string   `json:"descripcion,omitempty"`
	Latitud       *float64  `json:"latitud,omitempty"`
	Longitud      *float64  `json:"longitud,omitempty"`
	Orden         int32     `json:"orden"`
	FechaRegistro time.Time `json:"fecha_registro"`
}

type UpdNotificacion struct {
	ID      string    `json:"id"`
	Mensaje string    `json:"mensaje"`
	Desde   time.Time `json:"desde"`
	Hasta   time.Time `json:"hasta"`
}

type UpdUnidad struct {
	ID          string   `json:"id"`
	Nombre      string   `json:"nombre"`
	Descripcion *string  `json:"descripcion,omitempty"`
	Latitud     *float64 `json:"latitud,omitempty"`
	Longitud    *float64 `json:"longitud,omitempty"`
	Orden       int32    `json:"orden"`
}

type UpdatePerfil struct {
	ID        string   `json:"id"`
	Nombres   string   `json:"nombres"`
	Apellido1 string   `json:"apellido1"`
	Apellido2 *string  `json:"apellido2,omitempty"`
	Documento *string  `json:"documento,omitempty"`
	Celular   *string  `json:"celular,omitempty"`
	Correo    *string  `json:"correo,omitempty"`
	Sexo      *string  `json:"sexo,omitempty"`
	Direccion *string  `json:"direccion,omitempty"`
	Username  *string  `json:"username,omitempty"`
	Password  *string  `json:"password,omitempty"`
	Foto64    *string  `json:"foto64,omitempty"`
	Latitud   *float64 `json:"latitud,omitempty"`
	Longitud  *float64 `json:"longitud,omitempty"`
}

type UpdateRol struct {
	ID          string   `json:"id"`
	Nombre      string   `json:"nombre"`
	Descripcion *string  `json:"descripcion,omitempty"`
	Jerarquia   *int32   `json:"jerarquia,omitempty"`
	Permisos    []string `json:"permisos"`
	Menus       []int32  `json:"menus"`
}

type UpdateUsuario struct {
	ID              string       `json:"id"`
	Nombres         string       `json:"nombres"`
	Apellido1       string       `json:"apellido1"`
	Apellido2       *string      `json:"apellido2,omitempty"`
	Documento       *string      `json:"documento,omitempty"`
	Celular         *string      `json:"celular,omitempty"`
	Correo          *string      `json:"correo,omitempty"`
	Sexo            *string      `json:"sexo,omitempty"`
	Direccion       *string      `json:"direccion,omitempty"`
	Username        string       `json:"username"`
	Password        *string      `json:"password,omitempty"`
	Foto64          *string      `json:"foto64,omitempty"`
	Latitud         *float64     `json:"latitud,omitempty"`
	Longitud        *float64     `json:"longitud,omitempty"`
	Roles           []*RolUnidad `json:"roles"`
	PermisosSueltos []string     `json:"permisos_sueltos"`
	MenusSueltos    []string     `json:"menus_sueltos"`
}

type Usuario struct {
	ID            string     `json:"id"`
	Nombres       string     `json:"nombres"`
	Apellido1     string     `json:"apellido1"`
	Apellido2     *string    `json:"apellido2,omitempty"`
	Documento     *string    `json:"documento,omitempty"`
	Celular       *string    `json:"celular,omitempty"`
	Correo        *string    `json:"correo,omitempty"`
	Sexo          *string    `json:"sexo,omitempty"`
	Direccion     *string    `json:"direccion,omitempty"`
	Username      string     `json:"username"`
	FechaRegistro time.Time  `json:"fecha_registro"`
	FechaUpdate   time.Time  `json:"fecha_update"`
	Estado        bool       `json:"estado"`
	LastLogin     *time.Time `json:"last_login,omitempty"`
	OauthID       *string    `json:"oauth_id,omitempty"`
	FotoURL       *string    `json:"foto_url,omitempty"`
	Latitud       *float64   `json:"latitud,omitempty"`
	Longitud      *float64   `json:"longitud,omitempty"`
	Conexiones    int32      `json:"conexiones"`
}

type XNotificacion struct {
	Title    string `json:"title"`
	DataJSON string `json:"data_json"`
}
