// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package usuarios

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/dsaldias/server/graph_auth/model"
	"github.com/templui/templui/components/input"
)

func PerfilView(
	edit *model.ResponseUsuario,
) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- ID --><div class=\"hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:       "id",
			Name:     "id",
			Value:    edit.ID,
			Readonly: true,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"space-y-6\"><!-- DATOS PERSONALES --><div class=\"space-y-3\"><h3 class=\"text-sm font-semibold text-primary uppercase\">Datos personales</h3><div class=\"grid grid-cols-1 md:grid-cols-2 gap-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:          "nombres",
			Name:        "nombres",
			Placeholder: "Nombres",
			Value:       edit.Nombres,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:          "apellido1",
			Name:        "apellido1",
			Placeholder: "Primer apellido",
			Value:       edit.Apellido1,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:          "apellido2",
			Name:        "apellido2",
			Placeholder: "Segundo apellido",
			Value:       parseStringx(edit.Apellido2),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:          "documento",
			Name:        "documento",
			Placeholder: "Documento",
			Value:       parseStringx(edit.Documento),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><!-- CONTACTO --><div class=\"space-y-3\"><h3 class=\"text-sm font-semibold text-primary uppercase\">Contacto</h3><div class=\"grid grid-cols-1 md:grid-cols-2 gap-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:          "celular",
			Name:        "celular",
			Placeholder: "Celular",
			Value:       parseStringx(edit.Celular),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:          "correo",
			Name:        "correo",
			Type:        "email",
			Placeholder: "Correo electrónico",
			Value:       parseStringx(edit.Correo),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:          "direccion",
			Name:        "direccion",
			Placeholder: "Dirección",
			Value:       parseStringx(edit.Direccion),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:          "sexo",
			Name:        "sexo",
			Placeholder: "Sexo",
			Value:       parseStringx(edit.Sexo),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><!-- ACCESO --><div class=\"space-y-3\"><h3 class=\"text-sm font-semibold text-primary uppercase\">Acceso</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:          "username",
			Name:        "username",
			Placeholder: "Nombre de usuario",
			Value:       edit.Username,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:          "password",
			Name:        "password",
			Type:        "password",
			Placeholder: "Nueva contraseña",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<p class=\"text-xs text-muted-foreground\">Deja este campo vacío si no deseas cambiar tu contraseña.</p></div><!-- FOTO --><div class=\"space-y-3\"><h3 class=\"text-sm font-semibold text-primary uppercase\">Fotografía</h3><div class=\"flex flex-col sm:flex-row items-center gap-4\"><!-- Preview --><div id=\"foto_preview_container\" class=\"size-24 shrink-0 overflow-hidden rounded-full border bg-muted flex items-center justify-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if edit.FotoURL != nil && *edit.FotoURL != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<img id=\"foto_preview\" src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(*edit.FotoURL)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `dataadmin/pages/usuarios/editar.perfil.templ`, Line: 121, Col: 26}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" alt=\"Foto de perfil\" class=\"size-full object-cover\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<span id=\"foto_preview_placeholder\" class=\"text-xs text-muted-foreground text-center px-2\">Sin foto</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div><div class=\"space-y-2\"><input id=\"foto\" type=\"file\" accept=\"image/*\" class=\"block w-full text-sm file:mr-3 file:rounded-md file:border-0 file:bg-primary file:px-3 file:py-2 file:text-sm file:font-medium file:text-primary-foreground hover:file:bg-primary/90\"><p class=\"text-xs text-muted-foreground\">Selecciona una imagen para actualizar tu fotografía.</p></div></div><!-- Base64 --><div class=\"hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = input.Input(input.Props{
			ID:   "foto64",
			Name: "foto64",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div></div></div><script>\n\t(() => {\n\t\tconst fileInput = document.getElementById(\"foto\");\n\t\tconst foto64 = document.getElementById(\"foto64\");\n\t\tconst preview = document.getElementById(\"foto_preview\");\n\t\tconst placeholder = document.getElementById(\"foto_preview_placeholder\");\n\n\t\tif (!fileInput || !foto64) return;\n\n\t\tfileInput.addEventListener(\"change\", (event) => {\n\t\t\tconst file = event.target.files?.[0];\n\n\t\t\tif (!file) {\n\t\t\t\tfoto64.value = \"\";\n\t\t\t\treturn;\n\t\t\t}\n\n\t\t\tconst reader = new FileReader();\n\n\t\t\treader.onload = (e) => {\n\t\t\t\tconst dataUri = e.target.result;\n\n\t\t\t\tif (typeof dataUri !== \"string\") return;\n\n\t\t\t\tfoto64.value = dataUri;\n\n\t\t\t\tif (preview) {\n\t\t\t\t\tpreview.src = dataUri;\n\t\t\t\t\tpreview.classList.remove(\"hidden\");\n\t\t\t\t} else {\n\t\t\t\t\tconst img = document.createElement(\"img\");\n\t\t\t\t\timg.id = \"foto_preview\";\n\t\t\t\t\timg.alt = \"Foto de perfil\";\n\t\t\t\t\timg.className = \"size-full object-cover\";\n\t\t\t\t\timg.src = dataUri;\n\n\t\t\t\t\tdocument\n\t\t\t\t\t\t.getElementById(\"foto_preview_container\")\n\t\t\t\t\t\t.appendChild(img);\n\t\t\t\t}\n\n\t\t\t\tif (placeholder) {\n\t\t\t\t\tplaceholder.classList.add(\"hidden\");\n\t\t\t\t}\n\t\t\t};\n\n\t\t\treader.readAsDataURL(file);\n\t\t});\n\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
