package graph_auth

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/dsaldias/server/dataauth/repo"
	"github.com/dsaldias/server/graph_auth/model"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.NewLogin) (*model.ResponseLogin, error) {
	return repo.Login(ctx, r.DB, input)
}

// LoginV2 is the resolver for the login_v2 field.
func (r *mutationResolver) LoginV2(ctx context.Context, input model.NewLogin2) (*model.ResponseLogin, error) {
	return repo.LoginV2(ctx, r.DB, input)
}

// CreateRol is the resolver for the create_rol field.
func (r *mutationResolver) CreateRol(ctx context.Context, input model.NewRol) (*model.Rol, error) {
	return repo.CreateRol(ctx, r.DB, input)
}

// UpdateRol is the resolver for the update_rol field.
func (r *mutationResolver) UpdateRol(ctx context.Context, input model.UpdateRol) (*model.Rol, error) {
	return repo.UpdateRol(ctx, r.DB, input)
}

// CreateUsuario is the resolver for the create_usuario field.
func (r *mutationResolver) CreateUsuario(ctx context.Context, input model.NewUsuario) (*model.Usuario, error) {
	return repo.CreateUsuario(ctx, r.DB, input)
}

// UpdateUsuario is the resolver for the update_usuario field.
func (r *mutationResolver) UpdateUsuario(ctx context.Context, input model.UpdateUsuario) (*model.Usuario, error) {
	return repo.UpdateUsuario(ctx, r.DB, input)
}

// UpdatePerfil is the resolver for the update_perfil field.
func (r *mutationResolver) UpdatePerfil(ctx context.Context, input model.UpdatePerfil) (*model.Usuario, error) {
	return repo.UpdatePerfil(ctx, r.DB, input)
}

// CreateUnidad is the resolver for the create_unidad field.
func (r *mutationResolver) CreateUnidad(ctx context.Context, input model.NewUnidad) (*model.Unidad, error) {
	return repo.CreateUnidad(ctx, r.DB, input)
}

// UpdateUnidad is the resolver for the update_unidad field.
func (r *mutationResolver) UpdateUnidad(ctx context.Context, input model.UpdUnidad) (*model.Unidad, error) {
	return repo.UpdateUnidad(ctx, r.DB, input)
}

// CreateOauth is the resolver for the createOauth field.
func (r *mutationResolver) CreateOauth(ctx context.Context, input model.NewUsuarioOauth) (*model.Usuario, error) {
	return repo.CreateOauth(ctx, r.DB, input)
}

// EnviarNotificacion is the resolver for the enviar_notificacion field.
func (r *mutationResolver) EnviarNotificacion(ctx context.Context, titulo string) (bool, error) {
	return repo.EnviarNotificacion(ctx, r.DB, titulo)
}

// CrearNotificacion is the resolver for the crear_notificacion field.
func (r *mutationResolver) CrearNotificacion(ctx context.Context, input model.NewNotificacion) (*model.Notificacion, error) {
	return repo.CrearNotificacion(ctx, r.DB, input)
}

// UpdateNotificacion is the resolver for the update_notificacion field.
func (r *mutationResolver) UpdateNotificacion(ctx context.Context, input model.UpdNotificacion) (*model.Notificacion, error) {
	return repo.UpdateNotificacion(ctx, r.DB, input)
}

// CreateTicket is the resolver for the create_ticket field.
func (r *mutationResolver) CreateTicket(ctx context.Context, input model.NewTicket) (*model.Ticket, error) {
	return repo.CreateTicket(ctx, r.DB, input)
}

// UpdateTicket is the resolver for the update_ticket field.
func (r *mutationResolver) UpdateTicket(ctx context.Context, input model.NewTicketRespuesta) (*model.Ticket, error) {
	return repo.UpdateTicket(ctx, r.DB, input)
}

// CerrarTicket is the resolver for the cerrar_ticket field.
func (r *mutationResolver) CerrarTicket(ctx context.Context, id string) (*model.Ticket, error) {
	return repo.CerrarTicket(ctx, r.DB, id)
}

// ChatEnviarMensaje is the resolver for the chat_enviar_mensaje field.
func (r *mutationResolver) ChatEnviarMensaje(ctx context.Context, input model.ChatEnviarMensajeInput) (*model.ChatMensaje, error) {
	return repo.ChatEnviarMensaje(ctx, r.DB, input)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context, input model.InputMe) (*model.ResponseMe, error) {
	return repo.Me(ctx, r.DB, input)
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.ResponseRoles, error) {
	return repo.Roles(ctx, r.DB)
}

// Permisos is the resolver for the permisos field.
func (r *queryResolver) Permisos(ctx context.Context) ([]*model.Permiso, error) {
	return repo.Permisos(ctx, r.DB)
}

// Usuarios is the resolver for the usuarios field.
func (r *queryResolver) Usuarios(ctx context.Context, query model.QueryUsuarios) ([]*model.Usuario, error) {
	return repo.Usuarios(ctx, r.DB, query)
}

// UsuariosConectados is the resolver for the usuarios_conectados field.
func (r *queryResolver) UsuariosConectados(ctx context.Context) ([]*model.Usuario, error) {
	return repo.UsuariosConectados(ctx, r.DB)
}

// UsuarioByID is the resolver for the usuario_by_id field.
func (r *queryResolver) UsuarioByID(ctx context.Context, id string) (*model.ResponseUsuario, error) {
	return repo.UsuarioByID(ctx, r.DB, id)
}

// RolByID is the resolver for the rol_by_id field.
func (r *queryResolver) RolByID(ctx context.Context, id string) (*model.Rol, error) {
	return repo.RolByID(ctx, r.DB, id)
}

// Menus is the resolver for the menus field.
func (r *queryResolver) Menus(ctx context.Context) ([]*model.Menus, error) {
	return repo.Menus(ctx, r.DB)
}

// Unidades is the resolver for the unidades field.
func (r *queryResolver) Unidades(ctx context.Context) ([]*model.Unidad, error) {
	return repo.Unidades(ctx, r.DB)
}

// GetImagen is the resolver for the get_imagen field.
func (r *queryResolver) GetImagen(ctx context.Context, url string) (string, error) {
	return repo.GetImagen(ctx, r.DB, url)
}

// ConexionesWs is the resolver for the conexiones_ws field.
func (r *queryResolver) ConexionesWs(ctx context.Context) (string, error) {
	return repo.ConexionesWs(ctx, r.DB)
}

// Notificaciones is the resolver for the notificaciones field.
func (r *queryResolver) Notificaciones(ctx context.Context) ([]*model.Notificacion, error) {
	return repo.Notificaciones(ctx, r.DB)
}

// Reporte1 is the resolver for the reporte1 field.
func (r *queryResolver) Reporte1(ctx context.Context) ([]*model.ResponseReporte1, error) {
	return repo.Reporte1(ctx, r.DB)
}

// Reporte2 is the resolver for the reporte2 field.
func (r *queryResolver) Reporte2(ctx context.Context) ([]*model.ResponseReporte2, error) {
	return repo.Reporte2(ctx, r.DB)
}

// Reporte2b is the resolver for the reporte2b field.
func (r *queryResolver) Reporte2b(ctx context.Context) ([]*model.ResponseReporte2b, error) {
	return repo.Reporte2b(ctx, r.DB)
}

// AllTickets is the resolver for the all_tickets field.
func (r *queryResolver) AllTickets(ctx context.Context, q model.QueryTickets) ([]*model.RespTickets, error) {
	return repo.AllTickets(ctx, r.DB, q)
}

// MisTickets is the resolver for the mis_tickets field.
func (r *queryResolver) MisTickets(ctx context.Context) ([]*model.RespTickets, error) {
	return repo.MisTickets(ctx, r.DB)
}

// VerTicket is the resolver for the ver_ticket field.
func (r *queryResolver) VerTicket(ctx context.Context, id string) (*model.Ticket, error) {
	return repo.VerTicket(ctx, r.DB, id)
}

// ChatsByUser is the resolver for the chats_by_user field.
func (r *queryResolver) ChatsByUser(ctx context.Context, userID string) ([]*model.ResponseChatConversacion, error) {
	return repo.ChatsByUser(ctx, r.DB, userID)
}

// ChatMensajes is the resolver for the chat_mensajes field.
func (r *queryResolver) ChatMensajes(ctx context.Context, conversacionID string) ([]*model.ChatMensaje, error) {
	return repo.ChatMensajes(ctx, r.DB, conversacionID)
}

// ChatsNoLeidos is the resolver for the chats_no_leidos field.
func (r *queryResolver) ChatsNoLeidos(ctx context.Context, userID string) (int32, error) {
	return repo.ChatsNoLeidos(ctx, r.DB, userID)
}

// NotificacionesSubs is the resolver for the notificaciones_subs field.
func (r *subscriptionResolver) NotificacionesSubs(ctx context.Context) (<-chan *model.XNotificacion, error) {
	return repo.NotificacionesSubs(ctx, r.DB)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
