// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package utility

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/templui/templui/components/button"

type BtnProps struct {
	ModalTitle       string
	ModalDescription string
	HtmxGet          string
	HtmxPost         string
	DialogID         string
	Class            string
	Icon             templ.Component
	BtnText          string
	BtnSubmitText    string
	BtnCancelText    string
}

func ModalButton(p BtnProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			if p.Icon != nil {
				templ_7745c5c3_Err = p.Icon.Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if p.BtnText != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span class=\"btn-text\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(p.BtnText)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `dataadmin/admin/utility/modal_button.templ`, Line: 110, Col: 37}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			return nil
		})
		templ_7745c5c3_Err = button.Button(button.Props{
			Class:   classBtn(p),
			Size:    sizeBtn(p),
			Variant: button.VariantOutline,
			Attributes: templ.Attributes{
				"title":     p.ModalTitle,
				"hx-get":    p.HtmxGet,
				"hx-target": "#xcontenido-" + p.DialogID,
				"hx-swap":   "innerHTML",

				"hx-on::before-request": `
				this.dataset.originalContent = this.innerHTML;
				this.disabled = true;
				this.innerHTML = '<span class="animate-spin inline-block">↻</span>';
			`,
				"hx-on::send-error": ` 
				Toastify({
					text: 'No se pudo conectar con el servidor',
					style: {
						background: 'red',
						zIndex: 999999
					},
					duration: 5000,
					close: true,
					gravity: 'top',
					position: 'right'
				}).showToast();
			`,
				"xxxxxxhx-on::response-error": `
				Toastify({
					text: event.detail.xhr.responseText,
					style: {
						background: 'red',
						zIndex: 999999
					},
					duration: 5000,
					close: true,
					gravity: 'top',
					position: 'right'
				}).showToast();
			`,

				"hx-on::after-request": `
				this.disabled = false;
				this.innerHTML = this.dataset.originalContent;

				if (event.detail.successful) {
					const dialog = document.getElementById("` + p.DialogID + `");
					const titulo = dialog.querySelector("#titulo-` + p.DialogID + `");
					const descripcion = dialog.querySelector("#descripcion-` + p.DialogID + `");
					const btn_submit = dialog.querySelector("#btn-submit-` + p.DialogID + `");
					const btn_cancel = dialog.querySelector("#btn-cerrar-` + p.DialogID + `");
					const form = dialog.querySelector("#xform-` + p.DialogID + `");

					if (titulo) {
            titulo.textContent = "` + p.ModalTitle + `";
        	}
					if (descripcion) {
            descripcion.textContent = "` + p.ModalDescription + `";
        	}
					if (btn_submit) {
            btn_submit.style.display = "` + modalBtnSubmitDisplay(p) + `";

						if ("` + p.BtnSubmitText + `" != "") {
							const text = btn_submit.querySelector(".btn-submit-text");
							if (text) {
								text.textContent = "` + p.BtnSubmitText + `";
							}
						}
        	}
					if (btn_cancel) {
						if ("` + p.BtnCancelText + `" != "") {
							const text = btn_cancel.querySelector(".btn-cerrar-text");
							if (text) {
								text.textContent = "` + p.BtnCancelText + `";
							}
						}
        	}
					if (form) {
						form.setAttribute("hx-post", "` + p.HtmxPost + `");
						htmx.process(form);
					}
					window.tui.dialog.open("` + p.DialogID + `");
				}
			`,
			},
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func modalBtnSubmitDisplay(p BtnProps) string {
	if p.HtmxPost == "" {
		return "none"
	}
	return "flex"
}

func sizeBtn(p BtnProps) button.Size {
	if p.BtnText != "" && len(p.BtnText) > 0 {
		return button.SizeSm
	}
	return button.SizeIcon
}

func classBtn(p BtnProps) string {
	if p.Class == "" {
		return "hover:bg-[#e8f2f1]"
	}
	return p.Class
}

var _ = templruntime.GeneratedTemplate
